name: Package workflow
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          NPM_TOKEN: ${{secrets.TOKEN}}
      - run: export NPM_TOKEN="${{ secrets.TOKEN }}"
      - run: npm i
      - run: source ~/.profile
      - run: npm publish --access public